// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

open System
open DslAst
open TextUtilities
open Common
open Compilation
open System.Collections.Generic
open Errors
open Positioning
open DataStructures
open Navigation

let errorLogger = ErrorLogger()

let index = RedBlackTree<PosRange, IndexTerm>(PositionComparer.Instance)
let testIndex = PositionSet()

let addIdx posRange term = index.Insert(posRange, term)
let addTestIdx posRange term = testIndex.Insert(PositionIndex(posRange, term))

let separate lexems = 
    let rec separateRec (boolFlags1: BoolFlag1 list) (boolFlags2: BoolFlag2 list) (registrations:  Registration list) = function
        | (BoolFlag1(BoolFlag1.Flag(_) as b))::t -> 
            (b::boolFlags1, boolFlags2, registrations, t)  ||||> separateRec 
        | (BoolFlag2(BoolFlag2.Flag(_) as b))::t -> 
            (boolFlags1, b::boolFlags2, registrations, t)  ||||> separateRec
        | Registration(r)::t           -> 
            (boolFlags1, boolFlags2, List.append registrations r, t) ||||> separateRec
        | any::t -> (boolFlags1, boolFlags2, registrations, t) ||||> separateRec
        | []     -> (boolFlags1 |> List.rev, boolFlags2 |> List.rev, registrations)

    separateRec [] [] [] lexems

# 40 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | SNAME of (string)
  | FQN of (string)
  | DEPENDENCIES
  | MODULE
  | QUOT
  | FALSE
  | TRUE
  | BF2
  | BF1
  | EQ
  | ARROW
  | ERROR
  | TESTHEADER
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_SNAME
    | TOKEN_FQN
    | TOKEN_DEPENDENCIES
    | TOKEN_MODULE
    | TOKEN_QUOT
    | TOKEN_FALSE
    | TOKEN_TRUE
    | TOKEN_BF2
    | TOKEN_BF1
    | TOKEN_EQ
    | TOKEN_ARROW
    | TOKEN_ERROR
    | TOKEN_TESTHEADER
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_testBody
    | NONTERM_testHeader
    | NONTERM_expressionSet
    | NONTERM_bodyExpression
    | NONTERM_registration
    | NONTERM_registrationSet
    | NONTERM_boolFlag1
    | NONTERM_boolFlag2
    | NONTERM_errorBoolFlag1
    | NONTERM_errorBoolFlag2
    | NONTERM_errorRegistration
    | NONTERM_recover

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | SNAME _ -> 1 
  | FQN _ -> 2 
  | DEPENDENCIES  -> 3 
  | MODULE  -> 4 
  | QUOT  -> 5 
  | FALSE  -> 6 
  | TRUE  -> 7 
  | BF2  -> 8 
  | BF1  -> 9 
  | EQ  -> 10 
  | ARROW  -> 11 
  | ERROR  -> 12 
  | TESTHEADER  -> 13 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_SNAME 
  | 2 -> TOKEN_FQN 
  | 3 -> TOKEN_DEPENDENCIES 
  | 4 -> TOKEN_MODULE 
  | 5 -> TOKEN_QUOT 
  | 6 -> TOKEN_FALSE 
  | 7 -> TOKEN_TRUE 
  | 8 -> TOKEN_BF2 
  | 9 -> TOKEN_BF1 
  | 10 -> TOKEN_EQ 
  | 11 -> TOKEN_ARROW 
  | 12 -> TOKEN_ERROR 
  | 13 -> TOKEN_TESTHEADER 
  | 16 -> TOKEN_end_of_input
  | 14 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_start 
    | 3 -> NONTERM_testBody 
    | 4 -> NONTERM_testHeader 
    | 5 -> NONTERM_testHeader 
    | 6 -> NONTERM_testHeader 
    | 7 -> NONTERM_expressionSet 
    | 8 -> NONTERM_expressionSet 
    | 9 -> NONTERM_bodyExpression 
    | 10 -> NONTERM_bodyExpression 
    | 11 -> NONTERM_bodyExpression 
    | 12 -> NONTERM_bodyExpression 
    | 13 -> NONTERM_registration 
    | 14 -> NONTERM_registration 
    | 15 -> NONTERM_registration 
    | 16 -> NONTERM_registrationSet 
    | 17 -> NONTERM_registrationSet 
    | 18 -> NONTERM_boolFlag1 
    | 19 -> NONTERM_boolFlag1 
    | 20 -> NONTERM_boolFlag1 
    | 21 -> NONTERM_boolFlag2 
    | 22 -> NONTERM_boolFlag2 
    | 23 -> NONTERM_boolFlag2 
    | 24 -> NONTERM_errorBoolFlag1 
    | 25 -> NONTERM_errorBoolFlag1 
    | 26 -> NONTERM_errorBoolFlag1 
    | 27 -> NONTERM_errorBoolFlag1 
    | 28 -> NONTERM_errorBoolFlag2 
    | 29 -> NONTERM_errorBoolFlag2 
    | 30 -> NONTERM_errorBoolFlag2 
    | 31 -> NONTERM_errorBoolFlag2 
    | 32 -> NONTERM_errorRegistration 
    | 33 -> NONTERM_errorRegistration 
    | 34 -> NONTERM_errorRegistration 
    | 35 -> NONTERM_recover 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 16 
let _fsyacc_tagOfErrorTerminal = 14

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | SNAME _ -> "SNAME" 
  | FQN _ -> "FQN" 
  | DEPENDENCIES  -> "DEPENDENCIES" 
  | MODULE  -> "MODULE" 
  | QUOT  -> "QUOT" 
  | FALSE  -> "FALSE" 
  | TRUE  -> "TRUE" 
  | BF2  -> "BF2" 
  | BF1  -> "BF1" 
  | EQ  -> "EQ" 
  | ARROW  -> "ARROW" 
  | ERROR  -> "ERROR" 
  | TESTHEADER  -> "TESTHEADER" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | SNAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | FQN _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | DEPENDENCIES  -> (null : System.Object) 
  | MODULE  -> (null : System.Object) 
  | QUOT  -> (null : System.Object) 
  | FALSE  -> (null : System.Object) 
  | TRUE  -> (null : System.Object) 
  | BF2  -> (null : System.Object) 
  | BF1  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | ARROW  -> (null : System.Object) 
  | ERROR  -> (null : System.Object) 
  | TESTHEADER  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 1us; 65535us; 0us; 5us; 1us; 65535us; 5us; 6us; 2us; 65535us; 5us; 11us; 6us; 10us; 3us; 65535us; 5us; 22us; 6us; 22us; 14us; 23us; 2us; 65535us; 5us; 14us; 6us; 14us; 2us; 65535us; 5us; 12us; 6us; 12us; 2us; 65535us; 5us; 13us; 6us; 13us; 2us; 65535us; 5us; 28us; 6us; 28us; 2us; 65535us; 5us; 33us; 6us; 33us; 3us; 65535us; 5us; 21us; 6us; 21us; 14us; 21us; 3us; 65535us; 0us; 9us; 5us; 15us; 6us; 15us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 7us; 9us; 12us; 16us; 19us; 22us; 25us; 28us; 31us; 35us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 3us; 2us; 3us; 7us; 2us; 4us; 5us; 1us; 4us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 2us; 11us; 17us; 1us; 12us; 3us; 13us; 32us; 33us; 2us; 13us; 33us; 1us; 13us; 2us; 14us; 34us; 1us; 14us; 1us; 15us; 1us; 16us; 1us; 17us; 6us; 18us; 19us; 24us; 25us; 26us; 27us; 3us; 18us; 19us; 25us; 1us; 18us; 1us; 19us; 1us; 20us; 6us; 21us; 22us; 28us; 29us; 30us; 31us; 3us; 21us; 22us; 29us; 1us; 21us; 1us; 22us; 1us; 23us; 1us; 26us; 1us; 27us; 1us; 30us; 1us; 31us; 1us; 32us; 1us; 35us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 15us; 18us; 20us; 22us; 24us; 26us; 28us; 30us; 33us; 35us; 39us; 42us; 44us; 47us; 49us; 51us; 53us; 55us; 62us; 66us; 68us; 70us; 72us; 79us; 83us; 85us; 87us; 89us; 91us; 93us; 95us; 97us; 99us; |]
let _fsyacc_action_rows = 40
let _fsyacc_actionTableElements = [|3us; 32768us; 0us; 4us; 13us; 7us; 14us; 39us; 0us; 49152us; 1us; 32768us; 0us; 3us; 0us; 16385us; 0us; 16386us; 5us; 32768us; 2us; 16us; 4us; 19us; 8us; 29us; 9us; 24us; 14us; 39us; 5us; 16387us; 2us; 16us; 4us; 19us; 8us; 29us; 9us; 24us; 14us; 39us; 1us; 16389us; 1us; 8us; 0us; 16388us; 0us; 16390us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 2us; 16395us; 2us; 16us; 4us; 19us; 0us; 16396us; 2us; 32768us; 2us; 38us; 11us; 17us; 1us; 16417us; 2us; 18us; 0us; 16397us; 1us; 16418us; 2us; 20us; 0us; 16398us; 0us; 16399us; 0us; 16400us; 0us; 16401us; 3us; 16408us; 6us; 35us; 7us; 34us; 10us; 25us; 2us; 16409us; 6us; 27us; 7us; 26us; 0us; 16402us; 0us; 16403us; 0us; 16404us; 3us; 16412us; 6us; 37us; 7us; 36us; 10us; 30us; 2us; 16413us; 6us; 32us; 7us; 31us; 0us; 16405us; 0us; 16406us; 0us; 16407us; 0us; 16410us; 0us; 16411us; 0us; 16414us; 0us; 16415us; 0us; 16416us; 0us; 16419us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 7us; 8us; 9us; 15us; 21us; 23us; 24us; 25us; 26us; 27us; 28us; 29us; 32us; 33us; 36us; 38us; 39us; 41us; 42us; 43us; 44us; 45us; 49us; 52us; 53us; 54us; 55us; 59us; 62us; 63us; 64us; 65us; 66us; 67us; 68us; 69us; 70us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 2us; 2us; 1us; 1us; 2us; 1us; 1us; 1us; 1us; 1us; 3us; 2us; 1us; 1us; 2us; 3us; 3us; 1us; 3us; 3us; 1us; 1us; 2us; 2us; 2us; 1us; 2us; 2us; 2us; 2us; 2us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 2us; 3us; 3us; 3us; 4us; 4us; 5us; 5us; 5us; 5us; 6us; 6us; 6us; 7us; 7us; 8us; 8us; 8us; 9us; 9us; 9us; 10us; 10us; 10us; 10us; 11us; 11us; 11us; 11us; 12us; 12us; 12us; 13us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 65535us; 65535us; 65535us; 16388us; 16390us; 16391us; 16392us; 16393us; 16394us; 65535us; 16396us; 65535us; 65535us; 16397us; 65535us; 16398us; 16399us; 16400us; 16401us; 65535us; 65535us; 16402us; 16403us; 16404us; 65535us; 65535us; 16405us; 16406us; 16407us; 16410us; 16411us; 16414us; 16415us; 16416us; 16419us; |]
let _fsyacc_reductions ()  =    [| 
# 221 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : DslAst.DependencyTest)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 230 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'testBody)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "Parser.fsy"
                                          _1 
                   )
# 56 "Parser.fsy"
                 : DslAst.DependencyTest));
# 241 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "Parser.fsy"
                                 DependencyTest.Empty 
                   )
# 57 "Parser.fsy"
                 : DslAst.DependencyTest));
# 251 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'testHeader)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expressionSet)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "Parser.fsy"
                              
                                 (posRange parseState 1, _1 |> TestDeclarationTerm) ||> addIdx
                                 (posRange parseState 1, _1 |> TestDeclarationTerm) ||> addTestIdx
                                 let boolFlags1, boolFlags2, registrations = separate _2
                                 Test(_1, boolFlags1, boolFlags2, registrations, posRangeExt parseState 1 2)
                             
                   )
# 61 "Parser.fsy"
                 : 'testBody));
# 268 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "Parser.fsy"
                                              TestDeclaration.Full(_2, posRange parseState 1, posRange parseState 2) 
                   )
# 69 "Parser.fsy"
                 : 'testHeader));
# 279 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 71 "Parser.fsy"
                               
                                 (endPos parseState 1, ErrMsg.TestNameIsNotDefined, errorLogger) |||> reportPoint
                                 TestDeclaration.Partial(posRange parseState 1)
                             
                   )
# 71 "Parser.fsy"
                 : 'testHeader));
# 292 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'recover)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 75 "Parser.fsy"
                                     TestDeclaration.Error 
                   )
# 75 "Parser.fsy"
                 : 'testHeader));
# 303 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expressionSet)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'bodyExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 78 "Parser.fsy"
                                                          _2::_1 |> List.rev 
                   )
# 78 "Parser.fsy"
                 : 'expressionSet));
# 315 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'bodyExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 79 "Parser.fsy"
                                            [_1] 
                   )
# 79 "Parser.fsy"
                 : 'expressionSet));
# 326 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'boolFlag1)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 83 "Parser.fsy"
                                       
                                         (posRange parseState 1, _1 |> BoolFlag1Term) ||> addIdx
                                         (posRange parseState 1, _1 |> BoolFlag1Term) ||> addTestIdx
                                         BoolFlag1(_1)
                                     
                   )
# 83 "Parser.fsy"
                 : 'bodyExpression));
# 341 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'boolFlag2)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 89 "Parser.fsy"
                                       
                                         (posRange parseState 1, _1 |> BoolFlag2Term) ||> addIdx
                                         (posRange parseState 1, _1 |> BoolFlag2Term) ||> addTestIdx
                                         BoolFlag2(_1)
                                     
                   )
# 89 "Parser.fsy"
                 : 'bodyExpression));
# 356 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'registrationSet)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 94 "Parser.fsy"
                                             Registration(_1 |> List.rev) 
                   )
# 94 "Parser.fsy"
                 : 'bodyExpression));
# 367 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'recover)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 95 "Parser.fsy"
                                             Declaration.Error 
                   )
# 95 "Parser.fsy"
                 : 'bodyExpression));
# 378 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 98 "Parser.fsy"
                                               Class(_1, _3, posRange parseState 1, posRange parseState 2, posRange parseState 3) 
                   )
# 98 "Parser.fsy"
                 : 'registration));
# 390 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 99 "Parser.fsy"
                                               Module(_2, posRange parseState 1, posRange parseState 2) 
                   )
# 99 "Parser.fsy"
                 : 'registration));
# 401 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'errorRegistration)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 100 "Parser.fsy"
                                            _1 
                   )
# 100 "Parser.fsy"
                 : 'registration));
# 412 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'registration)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 103 "Parser.fsy"
                                         
                                            (posRange parseState 1, _1 |> RegistrationTerm) ||> addIdx
                                            (posRange parseState 1, _1 |> RegistrationTerm) ||> addTestIdx
                                            [_1]
                                        
                   )
# 103 "Parser.fsy"
                 : 'registrationSet));
# 427 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'registrationSet)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'registration)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 109 "Parser.fsy"
                                          
                                            (posRange parseState 2, _2 |> RegistrationTerm) ||> addIdx
                                            (posRange parseState 2, _2 |> RegistrationTerm) ||> addTestIdx
                                            _2::_1 
                                        
                   )
# 109 "Parser.fsy"
                 : 'registrationSet));
# 443 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 116 "Parser.fsy"
                                            BoolFlag1.Flag(true,  posRange parseState 1, startPos parseState 2, posRange parseState 3) 
                   )
# 116 "Parser.fsy"
                 : 'boolFlag1));
# 453 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 117 "Parser.fsy"
                                            BoolFlag1.Flag(false, posRange parseState 1, startPos parseState 2, posRange parseState 3) 
                   )
# 117 "Parser.fsy"
                 : 'boolFlag1));
# 463 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'errorBoolFlag1)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 118 "Parser.fsy"
                                            _1 
                   )
# 118 "Parser.fsy"
                 : 'boolFlag1));
# 474 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 121 "Parser.fsy"
                                            BoolFlag2.Flag(true,  posRange parseState 1, startPos parseState 2, posRange parseState 3) 
                   )
# 121 "Parser.fsy"
                 : 'boolFlag2));
# 484 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 122 "Parser.fsy"
                                            BoolFlag2.Flag(false, posRange parseState 1, startPos parseState 2, posRange parseState 3) 
                   )
# 122 "Parser.fsy"
                 : 'boolFlag2));
# 494 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'errorBoolFlag2)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 123 "Parser.fsy"
                                            _1 
                   )
# 123 "Parser.fsy"
                 : 'boolFlag2));
# 505 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 126 "Parser.fsy"
                                       
                                         (endPos parseState 1, ErrMsg.EqMissing, errorLogger) |||> reportPoint
                                         BoolFlag1.Error(BoolFlagMissingPart.Equal, endPos parseState 1) 
                                     
                   )
# 126 "Parser.fsy"
                 : 'errorBoolFlag1));
# 518 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 130 "Parser.fsy"
                                       
                                         (endPos parseState 2, ErrMsg.BoolMissing, errorLogger) |||> reportPoint
                                         BoolFlag1.Error(BoolFlagMissingPart.Value, endPos parseState 2) 
                                     
                   )
# 130 "Parser.fsy"
                 : 'errorBoolFlag1));
# 531 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 134 "Parser.fsy"
                                       
                                         (endPos parseState 1, ErrMsg.EqMissing, errorLogger) |||> reportPoint
                                         BoolFlag1.Error(BoolFlagMissingPart.Equal, endPos parseState 1) 
                                     
                   )
# 134 "Parser.fsy"
                 : 'errorBoolFlag1));
# 544 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 138 "Parser.fsy"
                                       
                                         (endPos parseState 1, ErrMsg.EqMissing, errorLogger) |||> reportPoint
                                         BoolFlag1.Error(BoolFlagMissingPart.Equal, endPos parseState 1) 
                                     
                   )
# 138 "Parser.fsy"
                 : 'errorBoolFlag1));
# 557 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 144 "Parser.fsy"
                                       
                                         (endPos parseState 1, ErrMsg.EqMissing, errorLogger) |||> reportPoint
                                         BoolFlag2.Error(BoolFlagMissingPart.Equal, endPos parseState 1) 
                                     
                   )
# 144 "Parser.fsy"
                 : 'errorBoolFlag2));
# 570 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 148 "Parser.fsy"
                                       
                                         (endPos parseState 2, ErrMsg.BoolMissing, errorLogger) |||> reportPoint
                                         BoolFlag2.Error(BoolFlagMissingPart.Value, endPos parseState 1) 
                                     
                   )
# 148 "Parser.fsy"
                 : 'errorBoolFlag2));
# 583 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 152 "Parser.fsy"
                                    
                                         (endPos parseState 1, ErrMsg.EqMissing, errorLogger) |||> reportPoint
                                         BoolFlag2.Error(BoolFlagMissingPart.Equal, endPos parseState 1) 
                                     
                   )
# 152 "Parser.fsy"
                 : 'errorBoolFlag2));
# 596 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 156 "Parser.fsy"
                                       
                                         (endPos parseState 1, ErrMsg.EqMissing, errorLogger) |||> reportPoint
                                         BoolFlag2.Error(BoolFlagMissingPart.Equal, endPos parseState 1) 
                                     
                   )
# 156 "Parser.fsy"
                 : 'errorBoolFlag2));
# 609 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 162 "Parser.fsy"
                                    
                                         (endPos parseState 1, ErrMsg.ArrowMissing, errorLogger) |||> reportPoint
                                         ClassError(ClassRegMissingPart.Arrow, endPos parseState 1) 
                                     
                   )
# 162 "Parser.fsy"
                 : 'errorRegistration));
# 624 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 166 "Parser.fsy"
                                    
                                         (endPos parseState 2, ErrMsg.FqnMissing, errorLogger) |||> reportPoint
                                         ClassError(ClassRegMissingPart.Name, endPos parseState 2) 
                                     
                   )
# 166 "Parser.fsy"
                 : 'errorRegistration));
# 638 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 170 "Parser.fsy"
                                    
                                         (endPos parseState 1, ErrMsg.FqnMissing, errorLogger) |||> reportPoint
                                         ModuleError(ModuleRegMissingPart.Name, endPos parseState 1) 
                                     
                   )
# 170 "Parser.fsy"
                 : 'errorRegistration));
# 651 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 177 "Parser.fsy"
                              
                                 let lexbuf   = parseState.ParserLocalStore.["LexBuffer"] :?> LexBuffer<char>
                                 let posRange = (lexbuf.StartPos, lexbuf.EndPos)
                                 let errToken = new string(lexbuf.Lexeme)
                                 (posRange, ErrMsg.UnexpectedToken errToken, errorLogger) |||>reportRange
                             
                   )
# 177 "Parser.fsy"
                 : 'recover));
|]
# 667 "Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 17;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : DslAst.DependencyTest =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
